rvm:
  - 2.1.1

cache: bundler

before_script:
  - 'phantomjs -v'

script:
  - 'bundle exec rake spec'

notifications:
  webhooks: https://ci.neighbor.ly/projects/bca4e45b-f539-42a6-a242-077a6f79b90b/status
