Dashboard.Project = DS.Model.extend
  name: DS.attr('string')
  permalink: DS.attr('string')
  category: DS.attr('string')
  user_id: DS.attr('string')
  goal: DS.attr('string')
  pledged: DS.attr('string')
  total_contributions: DS.attr('string')
  recommended: DS.attr('string')
  featured: DS.attr('string')
  home_page: DS.attr('string')
  online_date: DS.attr('date')
  expires_at: DS.attr('date')
  state: DS.attr('string')
