fr:
  words:
    are_you_sure_to_delete: 'Are you sure you want to delete this item?'
    no_results: 'No results'
    save: 'Save'
    cancel: 'Cancel'
    _yes: 'Yes'
    _no: 'No'
    search: 'Submit Search'
    search_results: 'Search Results'
    close: 'Close'
    okay: 'Okay'
